name: Randomize Columns in Dataset

on:
  push:
    branches:
      - main
    # paths:
    #   - 'data/*.xlsx'  # Trigger the workflow on new or modified CSV files in the 'data/' directory
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: 'write'
  id-token: write

###Set the new values for the randomized data set
env:
  LEFT_PROB_0: 0.4
  LEFT_PROB_1: 0.6
  WORK_ACCIDENT_PROB_0: 0.3
  WORK_ACCIDENT_PROB_1: 0.7
  SAT_LEVEL: 0.04
  EVAL_LEVEL: 0.04
  

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    ###Check out the repository
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        ###Get the current commit hash
      - name: Get current commit hash
        id: get_hash
        run: echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV        
        ###List the contents of the data directory
      - name: List contents of the data directory
        run: ls
        
        ###Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

        ###Install the necessary R library dependencies
      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::dplyr
            any::readxl
            
      - name: Run randomize columns R script
        run: |
          Rscript randomized_data_set.R ${{ env.commit_hash }} \
          $LEFT_PROB_0 $LEFT_PROB_1 \
          $WORK_ACCIDENT_PROB_0 $WORK_ACCIDENT_PROB_1 \
          $SAT_LEVEL $EVAL_LEVEL
          
      - name: List contents of the data directory
        run: ls data          
  
      - name: Upload modified dataset
        uses: actions/upload-artifact@v4
        with:
          name: modified-data
          path: data/
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit Changes
        run: |
          git add data/
          git commit -m "Add new analysis report for latest XLSX File"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
          
      - name: Print secret
        run: |
          echo "Vault URL: ${{ secrets.VAULT_URL }}"
        env:
          VAULT_URL: ${{ secrets.VAULT_URL }}
          
          
      - name: Get Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          role: github-actions-role
          method: jwt
          path: gh-actions
          secrets: |
            secret/data/gh-demo demo_secret          
