name: Randomize Columns in Dataset

on:
  push:
    branches:
      - main
    # paths:
    #   - 'data/*.xlsx'  # Trigger the workflow on new or modified CSV files in the 'data/' directory
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: 'write'

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Get current commit hash
        id: get_hash
        run: echo "commit_hash=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV        
        
      - name: List contents of the data directory
        run: ls
        

      - name: Set up R
        uses: r-lib/actions/setup-r@v2


      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::dplyr
            any::readxl

      - name: Run randomize columns R script
        run: |
          Rscript randomized_data_set.R ${{ env.commit_hash }}
          
      - name: List contents of the data directory
        run: ls data          
  
      - name: Upload modified dataset
        uses: actions/upload-artifact@v4
        with:
          name: modified-data
          path: data/
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit Changes
        run: |
          git add data/
          git commit -m "Add new analysis report for latest XLSX File"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
